name: veggy
favicon: null
layout_spectrum: 0.7299348816741258
typography_spectrum: 0.1911897857207805
title: veggy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5875742824282497
  lightness: 0.7233971366658807
  saturation: 0.6450294475071132
  rhythmicContrast: 0.6435916819609702
purpose: []
